<?php
	
	$localize = array(
		'signup' => array(
			'title' => 'Mulai trading',
			'coach' => "I'd like to speak with a trading coach",
			'active_submit' => 'Open account',
			'inactive_submit' => 'Not active',
			'type_account' => 'Type account',
			'real_account' => 'Akun pro',
			'demo_account' => 'Akun demo',
			'form_title' => 'Pendaftaran',
			'next' => 'Lebih Lanjut',
			'fill' => 'Isi',
			'choice_type_account' => 'Pilih jenis akun',
			'demo_account_text' => 'Memulai trading tanpa resiko',
			'real_account_text' => 'Akun Pro. Deposit minimal hanya $5',
			'by_register' => 'Mulai trading',
			'by_register_text' => '$1,000 telah ditambahkan kea kun demo Anda. Anda dapat mulai menggunakannya untuk trading sekarang juga, atau Anda bisa membuka akunPro riil untuk mendapatkan keuntungan yang sebenarnya.',
			'by_register_text_pro' => 'Akun Anda berhasil terdaftar. Untuk memulai trading Anda perlu melakukan deposit. Deposit minimum pada platform Optospot hanya $5.<br><br>Untuk membuat deposit Anda dapat menggunakan VISA / Mastercard atau sistem pembayaran yang Anda suka. Mulai trading sekarang.',
			'begin_trading' => 'Mulai trading',
			'active_submit_real' => 'REGISTER REAL ACCOUNT',
			'active_submit_demo' => 'REGISTER DEMO ACCOUNT',
			'try_for_free' => 'Try for free',
			'try_for_real' => 'Trade with real funds',
			'or' => 'or',
            'checkbox' => 'Saya menerima <a href="'.site_url('our-policies/optospot-terms-of-use').'" class="form-link">syarat dan ketentuan</a>'
		),
		'signin' => array(
			'login' => 'Log in',
			'forgot' => 'Forgot password?',
			'forgot_submit' => 'Lebih Lanjut',
			'error' => 'Login or passwrod is incorrect',
			'try_again' => 'Try again',
		),
		'user_block' => array(
			'hello' => 'Hello',
			'admin_link' => 'Administration Panel',
			'user_link' => 'My Account',
			'logoff' => 'Logout',
			'trader-balance' => 'Your balance',
			'fill-acc' => 'Fill balance'
		),
		'copyright' => array(
			'copy' => '2012-'.date('Y').' OptoSpot. All Rights Reserved',
			'development' => 'Developed by <a href="http://grphm.com/" target="_blank">&laquo;Grapheme&raquo;</a>'
		),
		'client_cabinet' => array(
			'page_name' => 'INFORMASI ACCOUNT',
			'demo_account' => 'Demo account',
			'register_real_account' => 'DAFTAR ACCOUNT RIIL',
			'register_demo_account' => 'Register demo account',
			'withdrawal' => 'Withdrawal request',
			'documents' => 'Download documents',
			'profile' => 'Profile',
			'balance' => 'Balance',
			'account' => 'Account',
			'deposit' => 'Deposit',
			'amount' => 'Amount',
			'deposit_funds' => 'Deposit Funds',
			'deposit_dengionline' => 'Deposit from Dengi Online',
			'deposit_rbkmoney' => 'Deposit from RBK Money',
			'deposit_submit_cancel' => 'Cancel',
			'my-accounts' => 'My accounts',
            'partner-program' => 'Partner program',
		),
		'withdraw' => array(
			'submit_withdraw' => 'Send request',
			'payment' => 'Choose payment',
			'holder_name' => 'Name',
			'account_number' => 'Specify the card number to withdraw money',
            'account_number_qiwi' => 'Specify the phone number to withdraw money',
			'expiry_date' => 'Expiry date',
		),
		'client_sidebar' => array(
			'navigation' => 'Navigation',
			'home' => 'Halaman Depan',
			'trade' => 'Trading',
			'deposit' => 'Deposit Info',
			'real_register' => 'Buka Account Riil',
			'demo_register' => 'Open demo account',
			'withdrawal' => 'Withdrawal',
			'profile' => 'Profil',
			'actions' => 'Actions',
			'logout' => 'Logout',
			'my-accounts' => 'Account Saya',
            'partner-program' => 'Partner program',
            'verification_off' => 'Verification',
            'verification_on' => 'Verified',
		),
		'form_profile' => array(
			'legend' => 'The form of editing profile. User login',
			'general_tab' => 'General',
			'address_tab' => 'Address',
			'advanced_tab' => 'Advanced',
			'fname_lable' => 'First name',
			'lname_lable' => 'Last name',
			'zip_lable' => 'Zip code',
			'day_phone_lable' => 'Day phone',
			'home_phone_lable' => 'Home phone',
			'signup_lable' => 'Date of sign up',
			'address1_lable' => 'Address line 1',
			'address2_lable' => 'Address line 2',
			'country_lable' => 'Country',
			'state_lable' => 'State',
			'city_lable' => 'City',
			'email_lable' => 'User email',
			'trade_login_lable' => 'Trade login',
			'trade_pass_lable' => 'Trade password',
			'submit' => 'Save profile',
		),
		'ticker' => array(
			'payout' => 'Payout',
			'amount' => 'Aayout',
			'winning_payout' => 'Winning payout',
			'minimum_payout' => 'Minimum payout',
			'above' => 'Above',
			'below' => 'Below',
			'invest' => 'Invest',
		),
		'user_documents' => array(
            'doc_link' => 'Document',
            'doc_date_upload' => 'Upload date',
            'doc_actions' => 'Action',
            'doc_action_upload' => 'Upload new',
            'documents_checked' => 'Checked',
            'documents_reject' => 'Rejected',
            'documents_approved' => 'Approved',
            'documents_rejected' => 'Click on the status "Rejected" to find out the reason why the document was not adopted',
            'doc_size' => 'Size',
            'doc_approved' => 'Status',
            'doc_approved_access' => 'Approved',
            'doc_approved_fail' => 'Not approved',
            'doc_approved_action' => 'Approve',
            'empty_list' => 'Documents not available',
            'upload_submit' => 'Upload',
            'identity_card' => 'Identity card',
            'identity_address' => 'Identity address',
		)
	);
	
?>