<?php
	
	$localize = array(
		'signup' => array(
			'title' => 'Начать торговать',
			'coach' => "Мне нужны первые консультации",
			'active_submit' => 'Открыть счет <span>Вы сможете выбрать демо или профи-счет</span>',
			'inactive_submit' => 'Не активно',
			'type_account' => 'Тип счета',
			'real_account' => 'Профи счет',
			'demo_account' => 'Демо счет',
			'form_title' => 'Регистрация',
			'next' => 'Далее',
			'fill' => 'Заполните форму',
			'choice_type_account' => 'Выберите тип счета',
			'demo_account_text' => 'Начни торговать без рисков',
			'real_account_text' => 'Минимальный депозит всего $5',
			'by_register' => 'Начните торговать',
			'by_register_text' => 'На ваш демо счет начислено 1000$. Вы можете начать торговать прямо сейчас или открыть профи-счет, чтобы ваш заработок стал реальным.',
			'by_register_text_pro' => 'Профи-аккаунт для вас успешно зарегистрирован. Для того чтобы начать торговать вам необходимо пополнить счет.<br><br>Минимальный депозит на платформе Optospot всего 5 долларов. Для пополнения счета вы можете использовать пластиковые карты или любую удобную вам платежную систему. Начните торговать прямо сейчас.',
			'begin_trading' => 'Начать торговать',
			'active_submit_real' => 'Регистрация профи-счета',
			'active_submit_demo' => 'Регистрация демо-счета',
			'try_for_free' => 'Попробовать бесплатно',
			'try_for_real' => 'торговать на реальные средства',
			'or' => 'или',
            'checkbox' => 'Я принимаю положения и <a href="'.site_url('our-policies/optospot-terms-of-use').'" class="form-link">условия</a>'
		),
		'signin' => array(
			'login' => 'Вход',
			'forgot' => 'Забыли пароль?',
			'forgot_submit' => 'Продолжить',
			'error' => 'Неправильные логин или пароль',
			'try_again' => 'Попробуйте еще',
		),
		'withdraw' => array(
			'submit_withdraw' => 'Отправить запрос',
			'payment' => 'Платежная система',
			'holder_name' => 'Имя держателя карты',
			'account_number' => 'Номер карты',
			'account_number_qiwi' => 'Номер телефона',
			'expiry_date' => 'Срок действия карты',
		),
		'user_block' => array(
			'hello' => 'Здравствуйте',
			'admin_link' => 'Администрирование',
			'user_link' => 'Мой аккаунт',
			'logoff' => 'Выход',
			'trader-balance' => 'Ваш баланс',
			'fill-acc' => 'Пополнить счет'
		),
		'copyright' => array(
			'annotation' => '<p>Предупреждение о рисках: Обратите внимание, что торговля Бинарными Опционами предполагает высокий уровень риска. Подобный род деятельности подходит не каждому инвестору. Вам не следует вкладывать средства, которые вы не можете позволить потерять, так как торговля может привести к полной потере инвестиций. Перед началом торговли вам следует ознакомиться со всеми рисками, связанными с торговлей Бинарными опционами.</p><p>ВНИМАНИЕ: OptoSpot не принимает жителей США. Граждане США (вне зависимости от места жительства) не могут открывать счета в нашей компании.</p>',
			'copy' => '2012-'.date('Y').' OptoSpot. Все права защищены',
			'development' => 'Разработанно агентством <a href="http://grapheme.ru/" target="_blank">&laquo;Графема&raquo;</a>',
		),
		'client_cabinet' => array(
			'page_name' => 'Личный кабинет',
			'demo_account' => 'Demo аккаунт',
			'register_real_account' => 'Открытие профи-счета',
			'register_demo_account' => 'Открытие демо-счета',
			'withdrawal' => 'Запрос на вывод средств',
			'documents' => 'Загрузка документов',
			'profile' => 'Профиль',
			'balance' => 'Баланс',
			'account' => 'Аккаунт',
			'deposit' => 'Счет',
			'amount' => 'Сумма',
			'deposit_funds' => 'Пополнить',
			'deposit_dengionline' => 'Пополнить через Dengi Online',
			'deposit_rbkmoney' => 'Пополнить через RBK Money',
			'deposit_submit_cancel' => 'Отменить оплату',
			'my-accounts' => 'Мои счета',
            'partner-program' => 'Партнерская программа',
            'verification' => 'Верификация',
		),
		'client_sidebar' => array(
			'navigation' => 'Навигация',
			'home' => 'На главную',
			'trade' => 'Начать торговать',
			'deposit' => 'Пополнить счет',
			'real_register' => 'Открыть профи-счет',
			'demo_register' => 'Открыть демо-счет',
			'withdrawal' => 'Вывод средств',
			'profile' => 'Профиль',
			'actions' => 'Действия',
			'logout' => 'Выход',
			'my-accounts' => 'Мои счета',
			'partner-program' => 'IB программа',
            'verification_off' => 'Верификация',
            'verification_on' => 'Верифицирован',
		),
		'form_profile' => array(
			'legend' => 'Редактирование профиля. Логин',
			'general_tab' => 'Основные',
			'address_tab' => 'Адреса',
			'advanced_tab' => 'Дополнительно',
			'fname_lable' => 'Имя',
			'lname_lable' => 'Фамилия',
			'zip_lable' => 'Индекс',
			'day_phone_lable' => 'Контактый телефон',
			'home_phone_lable' => 'Домашний телефон',
			'signup_lable' => 'Дата регистрации',
			'address1_lable' => 'Первая строка адреса',
			'address2_lable' => 'Вторая строка адреса',
			'country_lable' => 'Страна',
			'state_lable' => 'Область/штат',
			'city_lable' => 'Город',
			'email_lable' => 'Email',
			'trade_login_lable' => 'Логин',
			'trade_pass_lable' => 'Пароль',
			'submit' => 'Сохранить',
		),
		'ticker' => array(
			'payout' => 'Платеж',
			'amount' => 'Сумма',
			'winning_payout' => 'Заработок',
			'minimum_payout' => 'Минимальный платеж',
			'above' => 'Выше',
			'below' => 'Ниже',
			'invest' => 'Платеж',
		),
		'user_documents' => array(
            'doc_verification' => 'Верификация кабинета',
 			'doc_link' => 'Документ',
			'doc_date_upload' => 'Дата загрузки',
			'doc_actions' => 'Действие',
			'doc_action_upload' => 'Загрузить новый',
			'documents_checked' => 'Проверяется',
			'documents_approved' => 'Подтвержден',
			'documents_reject' => 'Отклонен',
			'documents_rejected' => 'Нажмите на статус "Отклонен", чтобы узнать причину, по которой документ не был принят',
			'doc_size' => 'Размер',
			'doc_approved' => 'Статус',
			'doc_approved_access' => 'Подтвержден',
			'doc_approved_fail' => 'Не подтвержден',
			'doc_approved_action' => 'Подтверждить',
			'empty_list' => 'Документы отсутствуют',
			'upload_submit' => 'Загрузить',
            'identity_card' => 'Удостоверение личности',
            'identity_address' => 'Удостоверение адреса',
            'reason_rejection' => 'Причина отклонения'
		)
	);
	
?>