<?php
	
	$localize = array(
		'signup' => array(
			'title' => 'Начать торговать',
			'coach' => "Мне нужны первые консультации",
			'active_submit' => 'Открыть счет <span>Вы сможете выбрать демо или профи-счет</span>',
			'inactive_submit' => 'Не активно',
			'type_account' => 'Тип счета',
			'real_account' => 'Профи счет',
			'demo_account' => 'Демо счет',
			'form_title' => 'Регистрация',
			'next' => 'Далее',
			'fill' => 'Заполните',
			'choice_type_account' => 'Выберите тип счета',
			'demo_account_text' => 'Начни торговать без рисков',
			'real_account_text' => 'Минимальный депозит всего за 5 $',
			'by_register' => 'Зарегистрируйтесь',
			'by_register_text' => 'На ваш демо счет начислено 1000$. Вы можете начать торговать прямо сейчас или открыть профи-счет, чтобы ваш заработок стал реальным.',
			'begin_trading' => 'Начать торговать',
		),
		'signin' => array(
			'login' => 'Вход',
			'forgot' => 'Забыли пароль?',
			'forgot_submit' => 'Продолжить',
		),
		'user_block' => array(
			'hello' => 'Здравствуйте',
			'admin_link' => 'Администрирование',
			'user_link' => 'Мой аккаунт',
			'logoff' => 'Выход'
		),
		'copyright' => array(
			'copy' => '2012-2013 OptoSpot. Все права защищены',
			'development' => 'Разработанно агенством &laquo;Графема&raquo;',
		),
		'client_cabinet' => array(
			'page_name' => 'Личный кабинет',
			'demo_account' => 'Demo аккаунт',
			'register_real_account' => 'Открытие профи-счета',
			'profile' => 'Профиль',
			'balance' => 'Баланс',
			'account' => 'Аккаунт',
			'deposit' => 'Счет',
			'amount' => 'Сумма',
			'deposit_funds' => 'Пополнить'
		),
		'client_sidebar' => array(
			'navigation' => 'Навигация',
			'home' => 'На главную',
			'trade' => 'Начать торговать',
			'deposit' => 'Пополнить счет',
			'real_register' => 'Профи-счет',
			'profile' => 'Профиль',
			'actions' => 'Действия',
			'logout' => 'Выход',
		),
		'form_profile' => array(
			'legend' => 'Редактирование профиля. Логин',
			'general_tab' => 'Основные',
			'address_tab' => 'Адреса',
			'advanced_tab' => 'Дополнительно',
			'fname_lable' => 'Имя',
			'lname_lable' => 'Фамилия',
			'zip_lable' => 'Индекс',
			'day_phone_lable' => 'Контактый телефон',
			'home_phone_lable' => 'Домашний телефон',
			'signup_lable' => 'Дата регистрации',
			'address1_lable' => 'Первая строка адреса',
			'address2_lable' => 'Вторая строка адреса',
			'country_lable' => 'Страна',
			'state_lable' => 'Область/штат',
			'city_lable' => 'Город',
			'email_lable' => 'Email',
			'trade_login_lable' => 'Логин',
			'trade_pass_lable' => 'Пароль',
			'submit' => 'Сохранить',
		),
		'ticker' => array(
			'payout' => 'Платеж',
			'amount' => 'Сумма',
			'winning_payout' => 'Заработок',
			'minimum_payout' => 'Минимальный платеж',
			'above' => 'Выше',
			'below' => 'Ниже',
			'invest' => 'Платеж',
		)
	);
	
?>