<?php
	
	$localize = array(
		'signup' => array(
			'title' => 'Start trading',
			'coach' => "I'd like to speak with a trading coach",
			'active_submit' => 'Open account',
			'inactive_submit' => 'Not active',
			'type_account' => 'Type account',
			'real_account' => 'Real account',
			'demo_account' => 'Demo account',
			'form_title' => 'registration',
			'next' => 'Next',
			'fill' => 'Fill the form',
			'choice_type_account' => 'Select type of account',
			'demo_account_text' => 'Start trading without risks',
			'real_account_text' => 'The minimum deposit is only $5',
			'by_register' => 'Start trading',
			'by_register_text' => 'In your demo account credited with $ 1,000. You can start trading right now or open a pro-account and your earnings become real.',
			'by_register_text_pro' => 'Your account successfully registered. In order to start trading you need to make a deposit. The minimum deposit on Optospot platform is only $5.<br><br>To make a deposit you can use VISA/Mastercard or any payment system you like. Start trading now.',
			'begin_trading' => 'Start trading',
			'active_submit_real' => 'REGISTER REAL ACCOUNT'
		),
		'signin' => array(
			'login' => 'Log in',
			'forgot' => 'Forgot password?',
			'forgot_submit' => 'Continue',
			'error' => 'Login or passwrod is incorrect',
			'try_again' => 'Try again',
		),
		'user_block' => array(
			'hello' => 'Hello',
			'admin_link' => 'Administration Panel',
			'user_link' => 'My Account',
			'logoff' => 'Logout',
			'trader-balance' => 'Your balance',
			'fill-acc' => 'Fill balance'
		),
		'copyright' => array(
			'copy' => '2012-2013 OptoSpot. All Rights Reserved',
			'development' => 'Developed by <a href="http://grphm.com/" target="_blank">&laquo;Grapheme&raquo;</a>'
		),
		'client_cabinet' => array(
			'page_name' => 'Account information',
			'demo_account' => 'Demo account',
			'register_real_account' => 'Register real account',
			'withdrawal' => 'Withdrawal request',
			'profile' => 'Profile',
			'balance' => 'Balance',
			'account' => 'Account',
			'deposit' => 'Deposit',
			'amount' => 'Amount',
			'deposit_funds' => 'Deposit Funds',
			'deposit_dengionline' => 'Deposit from Dengi Online',
			'deposit_rbkmoney' => 'Deposit from RBK Money',
			'deposit_submit_cancel' => 'Cancel'
		),
		'withdraw' => array(
			'submit_withdraw' => 'Send request',
			'payment' => 'Choose payment',
		),
		'client_sidebar' => array(
			'navigation' => 'Navigation',
			'home' => 'Home page',
			'trade' => 'Trade',
			'deposit' => 'Deposit Info',
			'real_register' => 'Real registration',
			'withdrawal' => 'Withdrawal',
			'profile' => 'Profile',
			'actions' => 'Actions',
			'logout' => 'Logout',
		),
		'form_profile' => array(
			'legend' => 'The form of editing profile. User login',
			'general_tab' => 'General',
			'address_tab' => 'Address',
			'advanced_tab' => 'Advanced',
			'fname_lable' => 'First name',
			'lname_lable' => 'Last name',
			'zip_lable' => 'Zip code',
			'day_phone_lable' => 'Day phone',
			'home_phone_lable' => 'Home phone',
			'signup_lable' => 'Date of sign up',
			'address1_lable' => 'Address line 1',
			'address2_lable' => 'Address line 2',
			'country_lable' => 'Country',
			'state_lable' => 'State',
			'city_lable' => 'City',
			'email_lable' => 'User email',
			'trade_login_lable' => 'Trade login',
			'trade_pass_lable' => 'Trade password',
			'submit' => 'Save profile',
		),
		'ticker' => array(
			'payout' => 'Payout',
			'amount' => 'Aayout',
			'winning_payout' => 'Winning payout',
			'minimum_payout' => 'Minimum payout',
			'above' => 'Above',
			'below' => 'Below',
			'invest' => 'Invest',
		)
	);
	
?>